### ISSUE TITLE
Include maildev service

### ISSUE THREAD

**Issue by raivisdejus** [scandipwa/create-magento-app#68]
Maildev lets developers catch all emails from local environment. This is useful for email template testing

On docker setup maildev can be acced with the following entry in `docker-compose.ymp`
```
  maildev:
    image: djfarrelly/maildev
    ports:
      - 1080:80
    expose:
      - 25
    restart: on-failure:5
```
and then on http://localhost:1080/ a "inbox" with all emails will be available
